#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config focused_border_color "#DD4C00"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a Galculator state=floating follow=on
bspc rule -a Thunar state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a File-roller state=floating follow=on
bspc rule -a Xreader state=floating follow=on
bspc rule -a vlc state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Geary desktop='^3'
bspc rule -a Screenkey manage=off

[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
pgrep -x panel > /dev/null || panel &

pkill xautolock
pkill compton

# AUTOSTART {
xautolock -time 5 -locker "/home/nachopro/.scripts/lock.sh" &
feh --bg-fill wallpaper.jpg &
compton &
# }
